        .import con_buf         ; console
        .import Rbuff           ; xmodem
        .import screen          ; display memory
        .import scrollbuf       ; text scroll buffer
        .import scrollbuf       ; vdp single line scroll buffer 900-920
        .import vdp_x           ; vdp console x
        .import vdp_y           ; vdp console y
        .import linebuf         ; vdp scroll line buffer
        .import scroll_read     ; vdp scroll read line num
        .import scroll_write    ; vdp scroll write line num